using STS2_Editor.Scripts.Editor.Graph;

namespace STS2_Editor.Scripts.Editor.Core.Models;

public sealed class EntityDraft
{
    public ModStudioEntityKind Kind { get; set; }

    public string EntityId { get; set; } = string.Empty;

    public BasicDraft Basic { get; set; } = new();

    public AssetDraft Assets { get; set; } = new();

    public GraphDraft Graph { get; set; } = new();
}

public sealed class BasicDraft
{
    public Dictionary<string, string> OriginalMetadata { get; set; } = new(StringComparer.Ordinal);

    public Dictionary<string, string> WorkingMetadata { get; set; } = new(StringComparer.Ordinal);

    public bool HasUserDescriptionOverride { get; set; }
}

public sealed class AssetDraft
{
    public string CurrentResolvedPath { get; set; } = string.Empty;

    public string CandidateResolvedPath { get; set; } = string.Empty;

    public string CandidateSourceType { get; set; } = string.Empty;

    public string CandidateAssetId { get; set; } = string.Empty;

    public AssetRef? CandidateAsset { get; set; }
}

public sealed class GraphDraft
{
    public bool UseGraphBehavior { get; set; }

    public string GraphId { get; set; } = string.Empty;

    public bool WasAutoGeneratedFromNative { get; set; }

    public string SelectedNodeId { get; set; } = string.Empty;

    public BehaviorGraphDefinition? WorkingGraph { get; set; }

    public BehaviorGraphDefinition? OriginalGraph { get; set; }
}
